Repository nextcloud/updater, pull requests merged in 2022-09, with the labels that each got.

#432 Check updater.phar is up to date in check-same-code-base job
  .github/workflows/check-same-code-base.yml
  updater.phar
Labels: 3. to review

#420 Introduce Update Directory
  index.php
  lib/Updater.php
Labels: enhancement, 3. to review

#433 Fix --version option
  .gitignore
  lib/CommandApplication.php
  lib/UpdateCommand.php
  updater.phar
Labels: 4. to release
