Repository nextcloud/updater, pull requests merged in 2023-02, with the labels that each got.

#461 Run make update.phar
  updater.phar
  vendor/composer/ClassLoader.php
  vendor/composer/autoload_real.php
Labels: 3. to review

#462 Run NC master test on > php7.4
  .github/workflows/check-same-code-base.yml
  .github/workflows/test-master.yml
Labels: 3. to review

#460 feat: Add --no-upgrade option to skip calling occ upgrade after update
  lib/UpdateCommand.php
  updater.phar
Labels: enhancement, 3. to review

#464 Revert "disable upgrades to 26 on 32-bit"
  index.php
  lib/Updater.php
  updater.phar
Labels: 3. to review, backport-request
