Repository nextcloud/updater, pull requests merged in 2024-05, with the labels that each got.

#555 Add further files which are going to ship with Nextcloud v30+
  .github/workflows/test-master.yml
  index.php
  lib/Updater.php
  updater.phar
Labels: 3. to review

#556 fix: Correctly check result of function
  index.php
  lib/Updater.php
  updater.phar
Labels: 3. to review

#564 fix(README): Add box installation + test run instructions
  README.md
Labels: 3. to review, technical debt, developer experience, docs

#569 docs(readme): Add instructions for passing "check same code base" test
  README.md
Labels: enhancement, 3. to review, developer experience
