Repository nextcloud/updater, pull requests merged in 2024-03, with the labels that each got.

#535 Also include *.config.php files
  index.php
  lib/Updater.php
  updater.phar
Labels: bug, 4. to release, feedback-requested

#534 [stable28] chore: update workflows from templates
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/psalm.yml
Labels: 3. to review, dependencies, automated

#540 Revert "Also include *.config.php files"
  index.php
  lib/Updater.php
  updater.phar
Labels: 3. to review
