Repository nextcloud/updater, pull requests merged in 2025-02, with the labels that each got.

#516 Improve iterators
  Makefile
  index.php
  index.web.php
  lib/RecursiveDirectoryIteratorWithoutData.php
  lib/Updater.php
  tests/features/master.feature
  updater.phar
  vendor/composer/InstalledVersions.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/composer/installed.php
  vendor/nextcloud/coding-standard/CHANGELOG.md
  vendor/nextcloud/coding-standard/README.md
  vendor/nextcloud/coding-standard/src/Config.php
  vendor/php-cs-fixer/shim/logo.md
  vendor/php-cs-fixer/shim/php-cs-fixer.phar
  vendor/php-cs-fixer/shim/php-cs-fixer.phar.asc
Labels: 2. developing

#595 fix(cli): occ error handling
  lib/UpdateCommand.php
  updater.phar
Labels: bug, 3. to review, feature: upgrade, mode: cli

#571 feat(updater): download resume w/ transfer statistics
  index.php
  lib/Updater.php
  updater.phar
Labels: enhancement, 3. to review, feature: download, feedback-requested

#579 fix: lock config file when reading and writing
  index.php
  lib/Updater.php
  tests/features/cli.feature
  updater.phar
Labels: bug, 3. to review, backport-request

#600 chore: Fix dependabot.yml
  .github/dependabot.yml
Labels: 3. to review, dependencies

#606 chore(deps): Bump behat and dependencies in tests/ folder
  .github/dependabot.yml
  Makefile
  REUSE.toml
  tests/composer.json
  vendor-bin/tests/composer.json
  vendor-bin/tests/composer.lock
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
Labels: 3. to review
